name: ios_game_center
description: A wrapper for iOS Game Center including auth and player info, leaderboard and more.
version: 0.0.10
homepage: https://github.com/jrmarkham/ios_game_center.git


environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: plugin.markhamenterprises.ios_game_center
        pluginClass: IOSGameCenterPlugin
      ios:
        pluginClass: IOSGameCenterPlugin

